const SECONDS = 1000;
// const MINUTES = 60 * SECONDS;

// Poller config
export const config = {
  NOTIFICATIONS_POLL_INTERVAL: 8 * SECONDS, // every 8 seconds
  NOTIFICATIONS_MAX_STALE_TIME: 5 * SECONDS,

  ROOM_THREADS_POLL_INTERVAL: 8 * SECONDS, // every 8 seconds
  ROOM_THREADS_MAX_STALE_TIME: 5 * SECONDS,

  USER_THREADS_POLL_INTERVAL: 8 * SECONDS, // every 8 seconds
  USER_THREADS_MAX_STALE_TIME: 5 * SECONDS,
};
